group 'co.eivo.brother_printer'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'co.eivo.brother_printer'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
    }
}

dependencies {
    implementation 'com.github.johnvuko:BrotherPrintLibrary:4.13.1'
}
